"""Phase 2 expansion roles for Boasted's zero-cost interview catalog.

Kept separate from the base seed so the catalog remains reviewable and easy to extend.
"""

PHASE2_CAREER_FAMILIES = {
    "customer-contact-center": [
        "Call Center Representative", "Customer Service Representative", "Contact Center Agent", "Inbound Call Center Representative", "Outbound Call Center Representative", "Customer Care Representative", "Member Services Representative", "Patient Access Representative", "Reservation Agent", "Telephone Operator", "Collections Representative", "Billing Representative", "Claims Representative", "Insurance Customer Service Representative", "Bank Customer Service Representative", "Technical Call Center Representative", "Customer Retention Specialist", "Escalation Specialist", "Service Desk Representative", "Dispatch Customer Service Representative", "Appointment Scheduler", "Intake Coordinator", "Order Support Representative", "E-commerce Customer Service Representative", "Chat Support Representative"],
    "administrative-office": [
        "Administrative Assistant", "Executive Assistant", "Receptionist", "Office Manager", "Office Assistant", "Data Entry Clerk", "File Clerk", "Records Clerk", "Mail Clerk", "Front Desk Coordinator", "Administrative Coordinator", "Operations Coordinator", "Scheduling Coordinator", "Unit Secretary", "Legal Secretary", "Medical Secretary", "Virtual Assistant", "Personal Assistant", "Document Control Specialist", "Records Management Specialist", "Office Administrator", "Clerical Assistant", "Program Assistant", "Department Coordinator", "Facilities Coordinator"],
    "retail-service": [
        "Cashier", "Store Associate", "Retail Associate", "Sales Associate", "Stock Associate", "Merchandise Associate", "Store Manager", "Assistant Store Manager", "Retail Supervisor", "Department Manager", "Visual Merchandiser", "Personal Shopper", "Grocery Clerk", "Produce Clerk", "Deli Clerk", "Bakery Clerk", "Meat Clerk", "Pharmacy Technician", "Loss Prevention Associate", "Asset Protection Specialist", "Store Receiver", "Inventory Associate", "Convenience Store Clerk", "Jewelry Sales Associate", "Mobile Sales Associate"],
    "hospitality-food": [
        "Restaurant Server", "Bartender", "Host", "Hostess", "Busser", "Food Runner", "Line Cook", "Prep Cook", "Sous Chef", "Executive Chef", "Dishwasher", "Barista", "Restaurant Manager", "Food Service Manager", "Catering Coordinator", "Banquet Server", "Hotel Front Desk Agent", "Hotel Manager", "Guest Services Agent", "Concierge", "Housekeeper", "Room Attendant", "Night Auditor", "Valet Attendant", "Event Coordinator"],
    "warehouse-logistics": [
        "Warehouse Associate", "Warehouse Worker", "Forklift Operator", "Material Handler", "Picker Packer", "Order Picker", "Shipping Clerk", "Receiving Clerk", "Shipping and Receiving Specialist", "Inventory Control Specialist", "Warehouse Supervisor", "Warehouse Manager", "Distribution Center Associate", "Logistics Coordinator", "Logistics Analyst", "Supply Chain Coordinator", "Supply Chain Analyst", "Procurement Specialist", "Purchasing Agent", "Buyer", "Dispatcher", "Route Coordinator", "Fleet Coordinator", "Delivery Driver", "Courier"],
    "transportation": [
        "Truck Driver", "CDL Driver", "Bus Driver", "School Bus Driver", "Transit Operator", "Taxi Driver", "Rideshare Driver", "Shuttle Driver", "Tow Truck Driver", "Delivery Route Driver", "Railroad Conductor", "Train Operator", "Locomotive Engineer", "Transportation Supervisor", "Transportation Manager", "Freight Broker", "Freight Coordinator", "Air Cargo Agent", "Ramp Agent", "Baggage Handler", "Flight Attendant", "Gate Agent", "Passenger Service Agent", "Aircraft Dispatcher", "Transportation Security Officer"],
    "healthcare-clinical": [
        "Certified Nursing Assistant", "Home Health Aide", "Patient Care Technician", "Nurse Practitioner", "Physician Assistant", "Emergency Medical Technician", "Paramedic", "Phlebotomist", "Medical Laboratory Technician", "Medical Laboratory Scientist", "Surgical Technologist", "Sterile Processing Technician", "Dialysis Technician", "EKG Technician", "Ultrasound Technologist", "MRI Technologist", "CT Technologist", "Nuclear Medicine Technologist", "Speech Language Pathologist", "Dietitian", "Nutritionist", "Behavioral Health Technician", "Mental Health Technician", "Clinical Research Coordinator", "Care Coordinator"],
    "healthcare-admin": [
        "Medical Receptionist", "Medical Biller", "Medical Coder", "Health Information Technician", "Medical Records Specialist", "Patient Services Representative", "Referral Coordinator", "Prior Authorization Specialist", "Insurance Verification Specialist", "Revenue Cycle Specialist", "Claims Processor", "Clinical Scheduler", "Practice Manager", "Clinic Manager", "Hospital Unit Coordinator", "Healthcare Quality Specialist", "Utilization Review Coordinator", "Credentialing Specialist", "Provider Enrollment Specialist", "Medical Office Manager", "Patient Advocate", "Patient Navigator", "Care Management Assistant", "Health Unit Coordinator", "Admissions Coordinator"],
    "insurance-banking": [
        "Bank Teller", "Personal Banker", "Universal Banker", "Loan Officer", "Mortgage Loan Officer", "Loan Processor", "Mortgage Processor", "Underwriter", "Insurance Underwriter", "Claims Adjuster", "Claims Examiner", "Claims Specialist", "Insurance Agent", "Insurance Producer", "Actuarial Analyst", "Credit Analyst", "Fraud Analyst", "AML Analyst", "KYC Analyst", "Credit Risk Analyst", "Market Risk Analyst", "Operational Risk Analyst", "Treasury Analyst", "Collections Specialist", "Financial Services Representative"],
    "human-resources": [
        "Human Resources Assistant", "Human Resources Coordinator", "Human Resources Generalist", "Human Resources Manager", "Recruiter", "Technical Recruiter", "Talent Acquisition Specialist", "Talent Acquisition Manager", "Sourcer", "Benefits Specialist", "Benefits Coordinator", "Compensation Analyst", "Payroll Specialist", "Payroll Coordinator", "Employee Relations Specialist", "Labor Relations Specialist", "Learning and Development Specialist", "Training Coordinator", "Training Manager", "HRIS Analyst", "People Operations Specialist", "People Operations Manager", "Onboarding Specialist", "Workforce Management Analyst", "Workforce Planning Analyst"],
    "legal-compliance": [
        "Paralegal", "Legal Assistant", "Attorney", "Associate Attorney", "Corporate Counsel", "Contract Specialist", "Contract Administrator", "Compliance Officer", "Compliance Specialist", "Regulatory Affairs Specialist", "Privacy Analyst", "Privacy Officer", "Legal Operations Specialist", "Court Clerk", "Judicial Assistant", "Probation Officer", "Correctional Officer", "Victim Advocate", "Mediator", "Title Examiner", "Title Processor", "Immigration Paralegal", "Litigation Paralegal", "Corporate Paralegal", "Risk and Compliance Analyst"],
    "public-safety-security": [
        "Security Officer", "Security Guard", "Security Supervisor", "Loss Prevention Officer", "Police Officer", "Police Dispatcher", "911 Dispatcher", "Firefighter", "Fire Inspector", "Emergency Management Specialist", "Emergency Management Coordinator", "Public Safety Officer", "Campus Safety Officer", "Corrections Officer", "Detention Officer", "Community Service Officer", "Code Enforcement Officer", "Animal Control Officer", "Park Ranger", "Lifeguard", "Crossing Guard", "Security Operations Center Operator", "Corporate Security Specialist", "Background Investigator", "Private Investigator"],
    "construction-trades": [
        "Construction Laborer", "Construction Manager", "Construction Project Manager", "General Contractor", "Painter", "Roofer", "Drywall Installer", "Flooring Installer", "Tile Installer", "Glazier", "Ironworker", "Sheet Metal Worker", "Pipefitter", "Steamfitter", "Boilermaker", "Millwright", "Heavy Equipment Operator", "Crane Operator", "Equipment Operator", "Solar Installer", "Wind Turbine Technician", "Elevator Technician", "Appliance Repair Technician", "Maintenance Technician", "Building Maintenance Worker"],
    "manufacturing": [
        "Production Worker", "Assembly Line Worker", "Assembler", "Machine Operator", "CNC Operator", "CNC Programmer", "Production Technician", "Manufacturing Technician", "Quality Inspector", "Quality Control Technician", "Quality Assurance Technician", "Production Supervisor", "Production Manager", "Manufacturing Engineer", "Process Engineer", "Industrial Engineer", "Maintenance Mechanic", "Electromechanical Technician", "Instrumentation Technician", "Controls Technician", "Packaging Operator", "Plant Operator", "Plant Manager", "Chemical Operator", "Process Operator"],
    "engineering": [
        "Mechanical Engineer", "Electrical Engineer", "Civil Engineer", "Chemical Engineer", "Industrial Engineer", "Manufacturing Engineer", "Aerospace Engineer", "Biomedical Engineer", "Environmental Engineer", "Structural Engineer", "Controls Engineer", "Automation Engineer", "Robotics Engineer", "Systems Engineer", "Hardware Engineer", "Firmware Engineer", "Test Engineer", "Validation Engineer", "Quality Engineer", "Reliability Engineer", "Field Engineer", "Applications Engineer", "Engineering Manager", "Engineering Technician", "CAD Designer"],
    "aviation": [
        "Commercial Pilot", "Airline Pilot", "First Officer", "Flight Instructor", "Aircraft Mechanic", "Aircraft Maintenance Technician", "Avionics Technician", "Aviation Maintenance Technician", "Aircraft Inspector", "Air Traffic Controller", "Airport Operations Specialist", "Airport Operations Manager", "Ground Operations Agent", "Aircraft Fueler", "Cabin Service Agent", "Crew Scheduler", "Flight Operations Coordinator", "Aviation Safety Inspector", "Aviation Security Specialist", "Aircraft Cleaner", "Load Planner", "Flight Dispatcher", "Airport Customer Service Agent", "Airline Operations Agent", "Aviation Manager"],
    "education-childcare": [
        "Elementary School Teacher", "Middle School Teacher", "High School Teacher", "Special Education Teacher", "Substitute Teacher", "Teaching Assistant", "Teacher Aide", "Preschool Teacher", "Daycare Teacher", "Childcare Worker", "Childcare Center Director", "School Administrator", "Assistant Principal", "Principal", "School Secretary", "School Nurse", "Librarian", "Library Assistant", "Tutor", "Academic Coach", "Admissions Counselor", "Financial Aid Advisor", "Registrar", "Student Services Coordinator", "Career Counselor"],
    "science-laboratory": [
        "Laboratory Technician", "Lab Assistant", "Research Assistant", "Research Associate", "Biologist", "Chemist", "Microbiologist", "Environmental Scientist", "Geologist", "Forensic Scientist", "Food Scientist", "Clinical Laboratory Scientist", "Quality Control Chemist", "Analytical Chemist", "Laboratory Manager", "Research Coordinator", "Clinical Research Associate", "Regulatory Scientist", "Biostatistician", "Epidemiologist", "Public Health Analyst", "Public Health Specialist", "GIS Analyst", "Geospatial Analyst", "Research Technician"],
    "media-creative": [
        "Copywriter", "Content Writer", "Technical Writer", "Editor", "Proofreader", "Journalist", "Reporter", "Photographer", "Videographer", "Video Editor", "Motion Graphics Designer", "Animator", "Illustrator", "Art Director", "Creative Director", "Producer", "Podcast Producer", "Audio Engineer", "Sound Designer", "Social Media Specialist", "Community Manager", "Communications Specialist", "Public Relations Specialist", "Public Relations Manager", "Content Creator"],
    "real-estate-property": [
        "Real Estate Agent", "Real Estate Broker", "Leasing Consultant", "Leasing Manager", "Property Manager", "Assistant Property Manager", "Community Manager", "Apartment Manager", "Maintenance Supervisor", "Facilities Manager", "Building Manager", "Real Estate Analyst", "Acquisitions Analyst", "Asset Manager", "Property Accountant", "Escrow Officer", "Escrow Assistant", "Title Agent", "Mortgage Underwriter", "Appraiser", "Home Inspector", "Property Inspector", "Real Estate Transaction Coordinator", "Commercial Property Manager", "HOA Manager"],
    "executive-management": [
        "General Manager", "Regional Manager", "District Manager", "Branch Manager", "Director of Operations", "Director of Engineering", "Director of Product", "Director of Marketing", "Director of Sales", "Director of Human Resources", "Vice President of Operations", "Vice President of Engineering", "Vice President of Product", "Vice President of Sales", "Chief Executive Officer", "Chief Operating Officer", "Chief Technology Officer", "Chief Financial Officer", "Chief Information Officer", "Chief Information Security Officer", "Managing Director", "Executive Director", "Department Director", "Area Manager", "Senior Operations Manager"],
}
