import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Pencil, Plus, Search, X } from "lucide-react";

import { createEntry, getEntries, updateEntry } from "./api";
import BragStackLoader from "./BragStackLoader.jsx";
import "./AccomplishmentsPage.css";

const PAGE_SIZE = 10;
const EDIT_WINDOW_MS = 60 * 60 * 1000;
const ENTRY_TYPES = ["Current Job", "Previous Job", "Personal Development", "Side Project", "Open Source", "Learning / Certification"];
const today = () => new Date().toISOString().slice(0, 10);
const emptyForm = () => ({ title: "", category: "", entry_date: today(), entry_type: "Current Job", situation: "", action: "", impact: "", lesson: "", tags: "", is_public: false });
function entryToForm(entry) { return { title: entry.title || "", category: entry.category || "", entry_date: entry.entry_date || today(), entry_type: entry.entry_type || "Current Job", situation: entry.situation || "", action: entry.action || "", impact: entry.impact || "", lesson: entry.lesson || "", tags: (entry.tags || []).join(", "), is_public: Boolean(entry.is_public) }; }
function getEditWindow(entry, nowMs) { if (!entry?.created_at) return { editable: false, minutesLeft: 0 }; const createdAtMs = new Date(entry.created_at).getTime(); if (!Number.isFinite(createdAtMs)) return { editable: false, minutesLeft: 0 }; const remainingMs = EDIT_WINDOW_MS - (nowMs - createdAtMs); return { editable: remainingMs > 0, minutesLeft: Math.max(0, Math.ceil(remainingMs / 60000)) }; }

function AccomplishmentsPage() {
  const [entries, setEntries] = useState([]); const [page, setPage] = useState(1); const [totalEntries, setTotalEntries] = useState(0); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState(""); const [searchTerm, setSearchTerm] = useState(""); const [showCreate, setShowCreate] = useState(() => new URLSearchParams(window.location.search).get("create") === "1"); const [editingEntry, setEditingEntry] = useState(null); const [form, setForm] = useState(emptyForm); const [isSaving, setIsSaving] = useState(false); const [createError, setCreateError] = useState(""); const [nowMs, setNowMs] = useState(() => Date.now());
  async function loadPage(targetPage = page) { setIsLoading(true); setError(""); try { const data = await getEntries(PAGE_SIZE, (targetPage - 1) * PAGE_SIZE); setEntries(data.entries ?? []); setTotalEntries(data.total_entries ?? 0); } catch (requestError) { if (requestError.response?.status === 401) { localStorage.removeItem("bragstack_token"); window.location.assign("/login"); return; } setError("BragStack could not load your accomplishments."); } finally { setIsLoading(false); } }
  useEffect(() => { const timeoutId = window.setTimeout(() => { void loadPage(page); }, 0); return () => window.clearTimeout(timeoutId); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [page]);
  useEffect(() => { const intervalId = window.setInterval(() => setNowMs(Date.now()), 30000); return () => window.clearInterval(intervalId); }, []);
  const totalPages = Math.max(1, Math.ceil(totalEntries / PAGE_SIZE)); const startEntry = totalEntries === 0 ? 0 : (page - 1) * PAGE_SIZE + 1; const endEntry = Math.min(page * PAGE_SIZE, totalEntries);
  const visibleEntries = useMemo(() => { const query = searchTerm.trim().toLowerCase(); if (!query) return entries; return entries.filter((entry) => [entry.title, entry.category, entry.entry_type, entry.situation, entry.action, entry.impact, entry.lesson, ...(entry.tags ?? [])].filter(Boolean).join(" ").toLowerCase().includes(query)); }, [entries, searchTerm]);
  const pageNumbers = useMemo(() => { const first = Math.max(1, page - 2); const last = Math.min(totalPages, first + 4); const adjustedFirst = Math.max(1, last - 4); return Array.from({ length: last - adjustedFirst + 1 }, (_, index) => adjustedFirst + index); }, [page, totalPages]);
  function openCreate() { setCreateError(""); setEditingEntry(null); setForm(emptyForm()); setShowCreate(true); window.history.replaceState({}, "", "/app/accomplishments?create=1"); }
  function openEdit(entry) { const editWindow = getEditWindow(entry, nowMs); if (!editWindow.editable) return; setCreateError(""); setEditingEntry(entry); setForm(entryToForm(entry)); setShowCreate(true); window.history.replaceState({}, "", `/app/accomplishments?edit=${encodeURIComponent(entry.id)}`); }
  function closeCreate() { setShowCreate(false); setEditingEntry(null); setCreateError(""); window.history.replaceState({}, "", "/app/accomplishments"); }
  function goToPage(nextPage) { const safePage = Math.min(Math.max(nextPage, 1), totalPages); setPage(safePage); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function handleFormChange(event) { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); }
  async function handleSave(event) { event.preventDefault(); setIsSaving(true); setCreateError(""); try { const payload = { ...form, tags: form.tags.split(",").map((tag) => tag.trim()).filter(Boolean) }; if (editingEntry) { const editWindow = getEditWindow(editingEntry, nowMs); if (!editWindow.editable) { setCreateError("The 60-minute edit window for this accomplishment has ended."); return; } await updateEntry(editingEntry.id, payload); } else await createEntry(payload); const wasEditing = Boolean(editingEntry); setForm(emptyForm()); closeCreate(); if (!wasEditing) setPage(1); await loadPage(wasEditing ? page : 1); } catch (requestError) { setCreateError(requestError.response?.data?.detail || `Your accomplishment could not be ${editingEntry ? "updated" : "saved"}.`); } finally { setIsSaving(false); } }
  const editingWindow = editingEntry ? getEditWindow(editingEntry, nowMs) : null;
  return <main className="accomplishments-page">
    <header className="accomplishments-hero"><div><p className="mini-label">Career Evidence Library</p><h1>Your accomplishments</h1><p>Browse the complete record of situations, actions, outcomes, skills, and public proof you have captured in BragStack.</p></div><button className="accomplishments-add" type="button" onClick={openCreate}><Plus size={18} /> Add accomplishment</button></header>
    {showCreate && <section className="modal-backdrop" onMouseDown={closeCreate}><form className="modal-card" onSubmit={handleSave} onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><p className="mini-label">{editingEntry ? "Edit career proof" : "New career proof"}</p><h2>{editingEntry ? "Edit accomplishment" : "Create accomplishment"}</h2>{editingWindow?.editable && <p className="edit-window-note">Editable for about {editingWindow.minutesLeft} more minute{editingWindow.minutesLeft === 1 ? "" : "s"}.</p>}</div><button type="button" className="icon-button" onClick={closeCreate} aria-label="Close"><X size={20} /></button></div>{createError && <div className="notice"><strong>Could not save</strong><span>{createError}</span></div>}<label>Title<input name="title" value={form.title} onChange={handleFormChange} required placeholder="What did you accomplish?" /></label><label>Category<input name="category" value={form.category} onChange={handleFormChange} required placeholder="Platform Engineering, Customer Support, Leadership…" /></label><div className="form-grid"><label>Date<input type="date" name="entry_date" value={form.entry_date} onChange={handleFormChange} required /></label><label>Type<select name="entry_type" value={form.entry_type} onChange={handleFormChange}>{ENTRY_TYPES.map((type) => <option key={type}>{type}</option>)}</select></label></div><label>Situation<textarea name="situation" value={form.situation} onChange={handleFormChange} required placeholder="What was happening?" /></label><label>Action<textarea name="action" value={form.action} onChange={handleFormChange} required placeholder="What did you specifically do?" /></label><label>Impact<textarea name="impact" value={form.impact} onChange={handleFormChange} required placeholder="What changed? Add numbers when you have them." /></label><label>Lesson<textarea name="lesson" value={form.lesson} onChange={handleFormChange} placeholder="What did you learn?" /></label><label>Skills / tags<input name="tags" value={form.tags} onChange={handleFormChange} placeholder="Docker, Python, Leadership" /></label><label className="checkbox-row"><input type="checkbox" name="is_public" checked={form.is_public} onChange={handleFormChange} /> Make this accomplishment public</label><div className="modal-actions"><button type="button" className="btn secondary" onClick={closeCreate}>Cancel</button><button type="submit" className="btn primary" disabled={isSaving || (editingEntry && !editingWindow?.editable)}>{isSaving ? "Saving…" : editingEntry ? "Save changes" : "Create accomplishment"}</button></div></form></section>}
    <section className="accomplishments-toolbar"><div className="accomplishments-search"><Search size={18} /><input value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} placeholder="Filter this page by skill, category, action, or impact..." /></div><p>Showing <strong>{startEntry}–{endEntry}</strong> of <strong>{totalEntries}</strong> accomplishments</p></section>
    {error && <div className="accomplishments-error">{error}</div>}
    {isLoading ? <BragStackLoader compact message="Loading your career proof…" detail="Gathering accomplishments, outcomes, skills, and evidence." /> : visibleEntries.length === 0 ? <section className="accomplishments-empty"><h2>No accomplishments found.</h2><p>{searchTerm ? "Try a different search on this page." : "Add your first accomplishment here to start building career proof."}</p>{!searchTerm && <button className="btn primary" type="button" onClick={openCreate}>Create accomplishment</button>}</section> : <section className="accomplishments-list">{visibleEntries.map((entry) => { const editWindow = getEditWindow(entry, nowMs); return <article className="accomplishment-card" key={entry.id}><div className="accomplishment-card-top"><div><p className="mini-label">{entry.category} • {entry.entry_type} • {entry.entry_date}</p><h2>{entry.title}</h2></div><div className="accomplishment-card-actions">{editWindow.editable ? <div className="accomplishment-edit-group"><button type="button" className="accomplishment-icon-action" onClick={() => openEdit(entry)} aria-label={`Edit ${entry.title}`} title={`Edit accomplishment · ${editWindow.minutesLeft} minutes left`}><Pencil size={17} /></button><span>{editWindow.minutesLeft}m left</span></div> : entry.created_at ? <span className="edit-window-locked">Edit window closed</span> : null}<span className={entry.is_public ? "proof-public" : "proof-private"}>{entry.is_public ? "Public proof" : "Private proof"}</span></div></div><p className="accomplishment-bullet">{entry.resume_bullet}</p><div className="accomplishment-proof-grid"><div><strong>Situation</strong><p>{entry.situation}</p></div><div><strong>Action</strong><p>{entry.action}</p></div><div><strong>Impact</strong><p>{entry.impact}</p></div>{entry.lesson && <div><strong>Lesson</strong><p>{entry.lesson}</p></div>}</div><div className="accomplishment-tags">{entry.tags?.map((tag) => <span key={tag}>{tag}</span>)}</div></article>; })}</section>}
    {totalPages > 1 && <nav className="pagination" aria-label="Accomplishments pages"><button type="button" onClick={() => goToPage(page - 1)} disabled={page === 1}><ChevronLeft size={17} /> Previous</button><div className="pagination-pages">{pageNumbers.map((pageNumber) => <button type="button" key={pageNumber} className={pageNumber === page ? "active" : ""} onClick={() => goToPage(pageNumber)}>{pageNumber}</button>)}</div><button type="button" onClick={() => goToPage(page + 1)} disabled={page === totalPages}>Next <ChevronRight size={17} /></button></nav>}
  </main>;
}
export default AccomplishmentsPage;
