import "./LegalPages.css";

const UPDATED = "September 8, 2026";

export function PublicFooter() {
  return (
    <footer className="legal-site-footer">
      <div className="legal-site-footer-grid">
        <div className="legal-site-footer-brand"><a href="/">Boasted</a><p>Turn everyday work into career proof you can use when it matters.</p></div>
        <div><h3>Product</h3><a href="/#product-impact-receipts">Impact Receipts</a><a href="/#product-career-analytics">Career Analytics</a><a href="/#product-reports">Reports</a><a href="/#pricing">Pricing</a></div>
        <div><h3>Resources</h3><a href="/docs">Docs</a><a href="/nda-safety">NDA & confidential work</a><a href="/#how-it-works">How it works</a><a href="/#security">Security</a></div>
        <div><h3>Company</h3><a href="mailto:Tobias.scott@boasted.io">Contact</a><a href="/login">Sign in</a><a href="/register">Create account</a></div>
        <div><h3>Legal</h3><a href="/privacy">Privacy Policy</a><a href="/terms">Terms & Conditions</a><a href="/nda-safety">Confidentiality guidance</a></div>
      </div>
      <div className="legal-site-footer-bottom"><span>© 2026 Boasted</span><span>Private by default · Your proof stays yours.</span></div>
    </footer>
  );
}

function LegalLayout({ title, intro, children }) {
  return (
    <main className="legal-page">
      <header className="legal-header"><a className="legal-brand" href="/">Boasted</a><nav aria-label="Legal navigation"><a href="/docs">Docs</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/nda-safety">NDA guidance</a><a href="/login">Sign in</a></nav></header>
      <article className="legal-card">
        <p className="legal-eyebrow">Boasted Legal</p><h1>{title}</h1><p className="legal-updated">Last updated: {UPDATED}</p><p className="legal-intro">{intro}</p>
        <div className="legal-callout">Boasted is built to help you document your work while keeping private career evidence private unless you choose to share it.</div>
        {children}
      </article>
      <PublicFooter />
    </main>
  );
}

export function PrivacyPolicyPage() {
  return <LegalLayout title="Privacy Policy" intro="This policy explains what Boasted collects, why we use it, how information may be shared, how long it may be retained, and the choices you have when using the Service.">
    <section><h2>1. Information we collect</h2><p>We collect information you provide directly, including your name, email address, authentication details, profile information, job targets, accomplishments, Impact Receipts, skills, measurable outcomes, notes, and evidence you upload, link, or reference.</p><p>We may also collect technical and usage data needed to operate and protect Boasted, such as IP address, device and browser information, timestamps, pages or features used, diagnostics, error logs, referring pages, approximate location derived from IP address, and essential cookie or local-storage data.</p></section>
    <section><h2>2. Career evidence and private workspace content</h2><p>Your private workspace is private by default. Accomplishments, drafts, evidence, generated career material, and other workspace content are not intended to be public unless a feature clearly supports sharing and you intentionally publish or share the item.</p><p>You are responsible for ensuring you are permitted to upload or reference workplace, client, customer, or third-party information. Boasted does not override your NDA, employment agreement, security policy, client contract, or legal obligations.</p></section>
    <section><h2>3. How we use information</h2><p>We use information to provide and secure Boasted; authenticate users; maintain accounts and preferences; store and organize career evidence; generate requested career materials; operate public and private sharing controls; process subscriptions; provide support; detect fraud and abuse; troubleshoot issues; measure product reliability; improve features; communicate important service or account information; and comply with applicable law.</p></section>
    <section><h2>4. AI-assisted features</h2><p>When you use an AI-assisted feature, the information necessary to perform that request may be processed by technology providers used to deliver the feature. Boasted is designed to ground career outputs in your recorded evidence rather than inventing accomplishments, credentials, employers, dates, or measurable results.</p><p>AI-generated material may still be incomplete, inaccurate, or unsuitable for a particular employer or application. You are responsible for reviewing generated content before using or sharing it.</p></section>
    <section><h2>5. Sharing and service providers</h2><p>We do not sell your personal information. We may disclose information to vendors and service providers that help us host infrastructure, authenticate users, process payments, deliver email, monitor reliability, analyze product usage, provide AI functionality, or otherwise operate the Service.</p><p>We may also disclose information when you direct us to share content, when reasonably necessary to comply with law or legal process, to enforce our agreements, to investigate fraud or security incidents, to protect rights or safety, or in connection with a merger, financing, acquisition, reorganization, or sale of assets subject to appropriate protections.</p></section>
    <section><h2>6. Payments and billing data</h2><p>Paid plans may be processed by a third-party payment processor such as Stripe. Boasted may receive billing identifiers, plan status, payment status, renewal information, and limited transaction metadata needed to manage your subscription. Full payment-card numbers should be collected and handled by the payment processor rather than stored directly by Boasted.</p></section>
    <section><h2>7. Cookies, local storage, analytics, and diagnostics</h2><p>Boasted may use cookies, browser storage, or similar technologies for authentication, account sessions, security, preferences, and core functionality. We may also use analytics or reliability tools to understand feature usage, page performance, errors, and confusing or broken product flows.</p><p>Boasted may use privacy-configured session replay for product diagnostics and usability analysis. Session replay reconstructs interactions with the Boasted interface from browser telemetry; it does not use your camera or microphone and is not video or audio recording of you.</p><p>We configure session replay to mask form inputs and rendered text and to block elements marked private or confidential. We do not intentionally use session replay to collect the contents of career evidence, private notes, passwords, authentication tokens, uploaded document contents, or network request and response bodies. Authenticated analytics may be associated with an internal account identifier rather than your name or email address.</p><p>Where required by law, non-essential technologies will be subject to appropriate notice, consent, or controls.</p></section>
    <section><h2>8. Public profiles and shared links</h2><p>If you intentionally publish a Proof Profile, share an Impact Receipt, or create another public or shareable link, recipients may view, copy, download, retain, or further share that information. Removing a public link later does not guarantee that copies already made by others will disappear.</p><p>Review your visibility settings and remove confidential, identifying, or sensitive information before sharing career proof publicly.</p></section>
    <section><h2>9. Receipt verification and verifier contact data</h2><p>If a Boasted user asks another person to verify an Impact Receipt, the user may provide that verifier’s name, email address, role, verification type, and an optional message. Boasted uses this information to deliver and manage the verification request and to present the verifier with the claim they were asked to review.</p><p>Pending verification contact data, including the verifier email, optional message, and hashed request token, is stored separately from the Impact Receipt and is scheduled for automatic deletion when the seven-day request period expires. When a verifier responds, Boasted deletes the pending contact payload and retains only the minimum attestation information needed to represent the response on the receipt, such as name, role, verification type, status, and response timestamps. A verifier does not need a Boasted account to respond.</p><p>If you receive a verification request and have a privacy question or request concerning your information, you may contact us using the address in this policy.</p></section>
    <section><h2>10. Data retention</h2><p>We retain information for as long as reasonably necessary to provide the Service, maintain account and security records, resolve disputes, enforce agreements, meet legal obligations, and support legitimate business needs. Different categories of data may have different retention periods, including the shorter retention period described above for pending receipt-verification contact data.</p><p>Deleted information may remain temporarily in backups, logs, or disaster-recovery systems until those systems cycle through their normal retention periods.</p></section>
    <section><h2>11. Account deletion and exports</h2><p>Where supported, you may request deletion of your account or a copy of your personal information. We may retain limited records where required for fraud prevention, billing, tax, legal compliance, security, or dispute resolution. Deleting an account does not necessarily delete information previously made public or copied by other users.</p><p>To request access, export, correction, or deletion, contact us using the address below. We may need to verify your identity before fulfilling a request.</p></section>
    <section><h2>12. Security</h2><p>We use reasonable administrative, technical, and organizational measures designed to protect information against unauthorized access, loss, misuse, or alteration. These measures may include authentication controls, access restrictions, encrypted connections, environment separation, secure vendor services, and monitoring practices appropriate to the product.</p><p>No online service can guarantee absolute security. You should use a strong, unique password, protect your sign-in provider accounts, and contact us promptly if you believe your Boasted account has been compromised.</p></section>
    <section><h2>13. Your privacy rights and choices</h2><p>Depending on where you live, you may have rights to access, correct, delete, export, restrict, or object to certain processing of personal information; withdraw consent where processing relies on consent; or appeal certain privacy decisions. We will honor applicable rights as required by law.</p><p>You may also control visibility of career proof using available product settings and may choose not to make any private item public.</p></section>
    <section><h2>14. Children</h2><p>Boasted is intended for people who are old enough to lawfully use online services and enter into these terms in their jurisdiction. We do not knowingly collect personal information from children who are not legally permitted to use the Service.</p></section>
    <section><h2>15. International processing</h2><p>If you access Boasted from outside the United States, your information may be processed in the United States and in other countries where our service providers operate. Those jurisdictions may have data-protection laws that differ from the laws where you live.</p></section>
    <section><h2>16. Business and legal disclosures</h2><p>If ownership or control of Boasted changes through a merger, financing, acquisition, reorganization, bankruptcy, or sale of assets, information may be transferred as part of that transaction, subject to applicable law and the commitments in this policy.</p></section>
    <section><h2>17. Changes to this policy</h2><p>We may update this Privacy Policy as Boasted evolves, new providers are added, or legal requirements change. We will post the revised version with a new “Last updated” date and provide additional notice when required.</p></section>
    <section><h2>18. Contact</h2><p>Questions, privacy requests, deletion requests, or data-access requests can be sent to <a href="mailto:Tobias.scott@boasted.io?subject=Boasted%20privacy%20request">Tobias.scott@boasted.io</a>.</p></section>
  </LegalLayout>;
}

export function TermsPage() {
  return <LegalLayout title="Terms and Conditions" intro="These Terms govern your access to and use of Boasted. By creating an account, purchasing a subscription, or otherwise using the Service, you agree to these Terms.">
    <section><h2>1. Eligibility and accounts</h2><p>You must be legally able to enter into these Terms and meet the minimum age required in your jurisdiction. You agree to provide accurate account information, keep credentials secure, and promptly notify us of suspected unauthorized access.</p><p>You are responsible for activity performed through your account unless prohibited by law.</p></section>
    <section><h2>2. What Boasted provides</h2><p>Boasted helps users record accomplishments and evidence, describe measurable impact, connect skills, control sharing, and turn recorded evidence into career materials such as performance-review packets, promotion material, resume content, interview preparation, and public proof.</p><p>Features may be added, removed, renamed, or changed as the product develops.</p></section>
    <section><h2>3. Your content and ownership</h2><p>You retain ownership of content you submit. You grant Boasted a limited, worldwide, non-exclusive license to host, store, reproduce, process, display, and otherwise use your content only as reasonably necessary to provide, secure, improve, maintain, and support the Service and the features you request.</p><p>This license does not give Boasted ownership of your accomplishments, evidence, or career history.</p></section>
    <section><h2>4. Confidentiality, NDAs, permissions, and verifier contacts</h2><p>You must have the rights and permissions necessary to upload, store, reference, or share your content. Do not upload trade secrets, confidential employer or client information, copyrighted material, regulated information, or other information you are not authorized to provide.</p><p>The receipt-verification feature may allow you to provide limited contact information about a collaborator, stakeholder, or organization representative so Boasted can send that person a verification request. You may use that feature only when you have a reasonable, lawful basis to provide the contact information for that purpose. Do not use verification requests for spam, harassment, marketing, retaliation, or unrelated contact, and do not provide more third-party information than the feature reasonably requires.</p><p>Outside features that expressly require limited third-party information, do not upload unnecessary personal data about other people. Boasted provides guidance for documenting sensitive work, but you remain responsible for complying with employer policies, NDAs, contracts, confidentiality obligations, and applicable law.</p></section>
    <section><h2>5. Acceptable use</h2><p>You may not use Boasted to violate law or another person’s rights; impersonate another person; distribute malware; interfere with security, availability, or performance; attempt unauthorized access; scrape or access the Service through unauthorized automated means; abuse trials or billing systems; distribute spam; harass others; or use Boasted to fabricate evidence, credentials, employment history, results, or accomplishments for fraudulent or deceptive purposes.</p></section>
    <section><h2>6. AI-assisted and generated career content</h2><p>AI-assisted and generated content is provided as a drafting and organization aid. It may be incomplete, inaccurate, outdated, or inappropriate for a particular employer or situation.</p><p>You are responsible for reviewing outputs before using them in resumes, applications, interviews, performance reviews, promotion discussions, client materials, or public profiles. Boasted does not guarantee employment, promotion, compensation, interview outcomes, hiring outcomes, or acceptance of generated material.</p></section>
    <section><h2>7. Subscriptions, billing, cancellation, and refunds</h2><p>Some features require a paid plan. Prices, included features, taxes, and billing intervals will be shown before purchase. Unless otherwise disclosed, subscriptions may renew automatically until canceled.</p><p>You may cancel future renewal through available billing controls or by contacting support. Cancellation generally stops future renewal and does not necessarily provide a refund for a period already paid. Except where required by law or expressly stated at purchase, fees already paid are non-refundable.</p><p>We may change prices or plan features with reasonable notice where required.</p></section>
    <section><h2>8. Free plans, trials, and feature limits</h2><p>Free plans, trials, promotional features, and usage limits may change over time. We may apply reasonable limits to storage, generated outputs, exports, receipts, integrations, or other features. We may discontinue or modify promotional access where permitted by law.</p></section>
    <section><h2>9. Public sharing</h2><p>If you intentionally publish a Proof Profile, Impact Receipt, or shareable link, you authorize Boasted to display that content to the intended audience. You are responsible for reviewing the content and its visibility before publishing it.</p><p>Boasted does not guarantee that information copied or retained by third parties can be removed after you stop sharing it.</p></section>
    <section><h2>10. Intellectual property</h2><p>Boasted’s software, design, branding, documentation, interfaces, and other materials provided by us are owned by Boasted or its licensors and are protected by applicable intellectual-property laws. These Terms do not transfer ownership of Boasted intellectual property to you.</p></section>
    <section><h2>11. Third-party services</h2><p>The Service may rely on or link to third-party providers for hosting, authentication, payment processing, analytics, email, AI features, or other infrastructure. Third-party services may have their own terms and privacy policies. Boasted is not responsible for products or services outside our control.</p></section>
    <section><h2>12. Suspension and termination</h2><p>You may stop using Boasted at any time. We may suspend or terminate access where reasonably necessary to address violations of these Terms, fraud, abuse, legal requirements, nonpayment, security threats, or material risk to the Service or others.</p><p>Where practical and legally permitted, we may provide notice or an opportunity to correct an issue before termination.</p></section>
    <section><h2>13. Service changes and availability</h2><p>We may add, remove, or modify features and may suspend parts of the Service for maintenance, security, reliability, or operational reasons. We do not promise that the Service will always be available, uninterrupted, or error-free.</p></section>
    <section><h2>14. Backups and data loss</h2><p>We may maintain backups and recovery systems, but you should not rely on Boasted as the sole repository for legally required, irreplaceable, or mission-critical records. To the extent permitted by law, you are responsible for retaining your own copies of important materials.</p></section>
    <section><h2>15. Disclaimers</h2><p>To the maximum extent permitted by law, the Service is provided “as is” and “as available.” Boasted disclaims warranties of merchantability, fitness for a particular purpose, non-infringement, and warranties arising from course of dealing or usage of trade, except where those warranties cannot legally be excluded.</p></section>
    <section><h2>16. Limitation of liability</h2><p>To the maximum extent permitted by law, Boasted and its owners, affiliates, employees, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenues, data, goodwill, or opportunities arising from or related to the Service.</p><p>To the maximum extent permitted by law, Boasted’s aggregate liability for claims relating to the Service will not exceed the greater of $100 or the amount you paid Boasted during the 12 months before the event giving rise to the claim. Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you.</p></section>
    <section><h2>17. Indemnification</h2><p>To the extent permitted by law, you agree to defend, indemnify, and hold harmless Boasted and its affiliates from claims, liabilities, damages, and reasonable expenses arising from your unlawful use of the Service, your content, or your material violation of these Terms or another person’s rights.</p></section>
    <section><h2>18. Governing law and disputes</h2><p>These Terms are governed by the laws of the State of Georgia, United States, without regard to conflict-of-law principles, except where applicable consumer law requires otherwise.</p><p>Before filing a formal claim, you and Boasted agree to make a good-faith effort to resolve the dispute informally. Any dispute not resolved informally will be handled in a court with appropriate jurisdiction in Georgia unless applicable law requires another forum.</p></section>
    <section><h2>19. Changes to these Terms</h2><p>We may update these Terms as Boasted changes. Revised Terms will be posted with a new effective date, and additional notice will be provided where required. Continued use after revised Terms become effective constitutes acceptance where permitted by law.</p></section>
    <section><h2>20. General terms</h2><p>If any provision is unenforceable, the remaining provisions remain effective. Failure to enforce a provision is not a waiver. You may not transfer these Terms without our consent; Boasted may transfer them as part of a merger, financing, reorganization, acquisition, or sale of the business. These Terms and incorporated policies form the agreement between you and Boasted concerning the Service.</p></section>
    <section><h2>21. Contact</h2><p>Questions about these Terms, billing, account access, or legal matters can be sent to <a href="mailto:Tobias.scott@boasted.io?subject=Boasted%20terms">Tobias.scott@boasted.io</a>.</p></section>
  </LegalLayout>;
}