import "./LegalPages.css";

const UPDATED = "August 23, 2026";

function LegalLayout({ title, intro, children }) {
  return (
    <main className="legal-page">
      <header className="legal-header">
        <a className="legal-brand" href="/">BragStack</a>
        <nav aria-label="Legal navigation">
          <a href="/privacy">Privacy</a>
          <a href="/terms">Terms</a>
          <a href="/login">Sign in</a>
        </nav>
      </header>
      <article className="legal-card">
        <p className="legal-eyebrow">BragStack Legal</p>
        <h1>{title}</h1>
        <p className="legal-updated">Last updated: {UPDATED}</p>
        <p className="legal-intro">{intro}</p>
        <div className="legal-callout">Plain-language summary: BragStack is built to help you document your work and control how it is shared. Your private career evidence is not public unless you choose to share it.</div>
        {children}
      </article>
      <footer className="legal-footer">© 2026 BragStack · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></footer>
    </main>
  );
}

export function PrivacyPolicyPage() {
  return (
    <LegalLayout title="Privacy Policy" intro="This Privacy Policy explains what information BragStack collects, why we use it, how it may be shared, and the choices you have when using our websites, applications, and related services (the “Service”).">
      <section><h2>1. Information we collect</h2><p>We collect information you provide directly, such as your name, email address, account credentials, profile information, job targets, accomplishments, Impact Receipts, skills, measurable outcomes, notes, and evidence you upload or link to the Service.</p><p>We may also collect technical and usage information such as IP address, browser and device information, pages or features used, timestamps, referring pages, approximate location derived from IP address, diagnostic information, and cookies or similar technologies needed to operate, secure, and understand the Service.</p></section>
      <section><h2>2. Career evidence and private content</h2><p>Your accomplishments, evidence, drafts, generated career materials, and other private workspace content are treated as private by default unless a feature clearly allows you to publish or share them and you choose to do so. You are responsible for ensuring that material you upload does not violate another person’s rights or disclose confidential employer, client, or third-party information you are not permitted to share.</p></section>
      <section><h2>3. How we use information</h2><p>We use information to provide and personalize BragStack; authenticate accounts; store and organize career evidence; generate performance-review packets, resumes, interview materials, and other requested outputs; operate sharing controls; process subscriptions; provide support; prevent abuse and fraud; troubleshoot and improve the Service; communicate important account or product information; and comply with law.</p></section>
      <section><h2>4. AI-assisted features</h2><p>When you use an AI-assisted feature, relevant content may be processed by the technology providers needed to perform your request. BragStack should use recorded evidence as the source for evidence-grounded career outputs rather than inventing accomplishments. AI output can still contain errors, so review generated material before relying on or sharing it.</p></section>
      <section><h2>5. How information is shared</h2><p>We do not sell your personal information. We may disclose information to service providers that help us host, secure, analyze, communicate, process payments, or operate the Service; when you direct us to share content; in connection with a merger, financing, acquisition, or sale of assets subject to appropriate protections; or when reasonably necessary to comply with law, enforce our agreements, or protect rights, safety, and security.</p></section>
      <section><h2>6. Payments</h2><p>If BragStack offers paid features, payment information may be collected and processed by a third-party payment processor. BragStack may receive transaction details such as subscription status, billing identifiers, and limited payment metadata, but should not need to store full payment-card numbers.</p></section>
      <section><h2>7. Cookies and analytics</h2><p>We may use essential cookies or local storage for authentication, security, preferences, and core functionality, and analytics technologies to understand product usage. Where required by law, we will request consent for non-essential cookies or provide appropriate controls.</p></section>
      <section><h2>8. Data retention</h2><p>We retain personal information for as long as reasonably necessary to provide the Service, maintain legitimate business and security records, resolve disputes, enforce agreements, and satisfy legal obligations. Retention periods may vary by data type. Deleted information may remain temporarily in backups or logs before being removed through normal retention cycles.</p></section>
      <section><h2>9. Security</h2><p>We use reasonable administrative, technical, and organizational safeguards designed to protect information. No internet service can guarantee absolute security, so you should use a strong unique password and protect your account credentials.</p></section>
      <section><h2>10. Your choices and privacy rights</h2><p>Depending on where you live, you may have rights to access, correct, delete, export, restrict, or object to certain processing of personal information, or to withdraw consent where processing relies on consent. You may also update information through available account controls. We may need to verify your identity before fulfilling certain requests.</p></section>
      <section><h2>11. Public and shared content</h2><p>If you deliberately publish a profile, share an Impact Receipt, create a public link, or otherwise make content available to others, recipients may view, copy, or retain that information. Review sharing settings and remove confidential evidence before publishing.</p></section>
      <section><h2>12. Children</h2><p>BragStack is intended for people who are at least 13 years old, or the higher minimum age required to use online services in their jurisdiction. We do not knowingly collect personal information from children who are not legally permitted to use the Service.</p></section>
      <section><h2>13. International use</h2><p>If you access BragStack from outside the United States, your information may be processed in the United States and other countries where our service providers operate. Those locations may have different data-protection laws than your country.</p></section>
      <section><h2>14. Changes to this policy</h2><p>We may update this Privacy Policy as BragStack evolves. We will post the revised policy with a new “Last updated” date and, when required, provide additional notice of material changes.</p></section>
      <section><h2>15. Contact</h2><p>Questions or privacy requests can be sent to <a href="mailto:privacy@usebragstack.com">privacy@usebragstack.com</a>.</p></section>
    </LegalLayout>
  );
}

export function TermsPage() {
  return (
    <LegalLayout title="Terms and Conditions" intro="These Terms and Conditions (“Terms”) govern your access to and use of BragStack. By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use the Service.">
      <section><h2>1. Eligibility and accounts</h2><p>You must be legally able to enter into these Terms and meet the minimum age required in your jurisdiction. You agree to provide accurate account information, keep credentials secure, and promptly notify us of suspected unauthorized access. You are responsible for activity performed through your account.</p></section>
      <section><h2>2. What BragStack provides</h2><p>BragStack helps users record accomplishments and supporting evidence, describe measurable impact, connect skills, control sharing, and turn recorded evidence into career materials such as performance-review packets, resume content, and interview preparation. Features may change as the product develops.</p></section>
      <section><h2>3. Your content and ownership</h2><p>You retain ownership of content you submit to BragStack. You grant BragStack a limited, worldwide, non-exclusive license to host, store, reproduce, process, display, and otherwise use your content only as reasonably necessary to provide, secure, improve, and support the Service and the features you request. This license ends when the content is deleted except where retention is reasonably necessary for backups, legal obligations, security, or dispute resolution.</p></section>
      <section><h2>4. Evidence, confidentiality, and permissions</h2><p>You represent that you have the rights and permissions necessary to upload or share your content. Do not upload trade secrets, confidential employer or client information, personal data about others, copyrighted material, or other information you are not authorized to provide. BragStack does not determine whether your workplace permits particular information to be stored or shared.</p></section>
      <section><h2>5. Acceptable use</h2><p>You may not use the Service to violate law or another person’s rights; impersonate others; submit malicious code; interfere with security or availability; scrape or access the Service through unauthorized automated means; attempt to gain unauthorized access; abuse free trials or billing systems; distribute spam; or use BragStack to fabricate evidence, credentials, employment history, or accomplishments for fraudulent purposes.</p></section>
      <section><h2>6. AI-generated and career content</h2><p>AI-assisted and generated content is provided as a drafting aid and may be incomplete or inaccurate. You are responsible for reviewing outputs before using them in applications, performance reviews, interviews, or other professional settings. BragStack does not guarantee employment, promotion, compensation, interview outcomes, or acceptance of any generated material.</p></section>
      <section><h2>7. Subscriptions, billing, and cancellation</h2><p>Certain features may require a paid subscription. Prices, billing intervals, included features, and applicable taxes will be shown before purchase. Unless otherwise stated, subscriptions renew automatically until canceled. You may cancel future renewal through the available account or billing controls. Except where required by law or expressly stated at purchase, fees already paid are non-refundable.</p></section>
      <section><h2>8. Intellectual property</h2><p>BragStack and its software, design, branding, documentation, and other materials provided by us are owned by BragStack or its licensors and are protected by applicable intellectual-property laws. These Terms do not transfer ownership of BragStack intellectual property to you.</p></section>
      <section><h2>9. Third-party services</h2><p>The Service may rely on or link to third-party services, including hosting, authentication, payment, analytics, and AI providers. Their services may be governed by separate terms and privacy policies. We are not responsible for third-party products or services outside our control.</p></section>
      <section><h2>10. Suspension and termination</h2><p>You may stop using BragStack at any time. We may suspend or terminate access when reasonably necessary to address violations of these Terms, security threats, fraud, legal requirements, nonpayment, or material risk to the Service or others. Where practical, we will provide notice.</p></section>
      <section><h2>11. Service changes and availability</h2><p>We may add, remove, or modify features and may suspend parts of the Service for maintenance, security, or operational reasons. We do not promise that the Service will always be available, uninterrupted, or error-free.</p></section>
      <section><h2>12. Disclaimers</h2><p>To the maximum extent permitted by law, the Service is provided “as is” and “as available.” BragStack disclaims warranties of merchantability, fitness for a particular purpose, non-infringement, and any warranties arising from course of dealing or usage of trade. Nothing in these Terms excludes warranties that cannot legally be excluded.</p></section>
      <section><h2>13. Limitation of liability</h2><p>To the maximum extent permitted by law, BragStack and its owners, affiliates, employees, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenues, data, goodwill, or opportunities arising from the Service. To the maximum extent permitted by law, BragStack’s aggregate liability for claims relating to the Service will not exceed the greater of $100 or the amount you paid BragStack during the 12 months before the event giving rise to the claim. Some jurisdictions do not allow certain limitations, so portions of this section may not apply to you.</p></section>
      <section><h2>14. Indemnification</h2><p>To the extent permitted by law, you agree to defend, indemnify, and hold harmless BragStack and its affiliates from claims, liabilities, damages, and reasonable expenses arising from your unlawful use of the Service, your content, or your material violation of these Terms or another person’s rights.</p></section>
      <section><h2>15. Governing law and disputes</h2><p>These Terms are governed by the laws of the State of Georgia, United States, without regard to conflict-of-law principles, except where applicable consumer law requires otherwise. Before filing a formal claim, you and BragStack agree to make a good-faith effort to resolve the dispute informally by contacting the other party. Any dispute not resolved informally will be handled in courts with appropriate jurisdiction in Georgia unless applicable law requires another forum.</p></section>
      <section><h2>16. Changes to these Terms</h2><p>We may update these Terms as the Service changes. We will post revised Terms with a new effective date and provide additional notice when required. Continued use after revised Terms become effective constitutes acceptance where permitted by law.</p></section>
      <section><h2>17. General terms</h2><p>If a provision is unenforceable, the remaining provisions remain effective. Failure to enforce a provision is not a waiver. You may not transfer these Terms without our consent; BragStack may transfer them as part of a reorganization, financing, merger, acquisition, or sale of the business. These Terms and incorporated policies form the agreement between you and BragStack concerning the Service.</p></section>
      <section><h2>18. Contact</h2><p>Questions about these Terms can be sent to <a href="mailto:legal@usebragstack.com">legal@usebragstack.com</a>.</p></section>
    </LegalLayout>
  );
}
