import { PublicFooter } from "./LegalPages.jsx";
import "./LegalPages.css";

function NDAGuidancePage() {
  return (
    <main className="legal-page">
      <header className="legal-header"><a className="legal-brand" href="/">BragStack</a><nav aria-label="NDA guidance navigation"><a href="/docs">Docs</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/security">Security</a><a href="/login">Sign in</a></nav></header>
      <article className="legal-card">
        <p className="legal-eyebrow">BragStack Safety Guidance</p>
        <h1>Using BragStack with confidential, restricted, and third-party information</h1>
        <p className="legal-updated">Last updated: September 4, 2026</p>
        <p className="legal-intro">BragStack can help you preserve the career or education value of real work without copying secrets into a new system. Your NDA, confidentiality agreement, employer policy, client agreement, school rule, security requirement, intellectual-property obligation, or law always comes first.</p>
        <div className="legal-callout">Capture the signal, not the secret. If you are not clearly allowed to store information outside its original system, do not put it in BragStack.</div>
        <section><h2>1. BragStack does not override your obligations</h2><p>Private-by-default controls do not create permission to retain or disclose information. You are responsible for understanding the agreements, policies, laws, and professional duties that apply to your work, education, applications, clients, employers, schools, and third parties.</p></section>
        <section><h2>2. Generalize sensitive context</h2><p>Prefer descriptions such as “enterprise customer,” “internal platform,” “regulated workload,” “selective program,” or “research project” instead of confidential names, code names, internal URLs, repository names, architecture details, customer identifiers, student identifiers, unreleased product information, private incident details, or restricted program material.</p></section>
        <section><h2>3. Do not copy restricted evidence</h2><p>Do not upload screenshots, tickets, logs, source code, documents, messages, contracts, credentials, customer records, student records, recommendation letters, internal grading material, proprietary prompts, private application-review notes, or attachments unless you are authorized to store and reuse them outside the original system.</p></section>
        <section><h2>4. Highly sensitive data does not belong here</h2><p>Do not put passwords, API keys, access tokens, full card numbers, bank credentials, Social Security or national-identification numbers, government-ID images, medical records, biometric identifiers, background-check material, classified information, or similarly sensitive data into BragStack.</p><p>Do not assume BragStack is approved for a regulated data category merely because it offers security features. Any specific compliance status must be stated expressly in current official materials or a signed agreement.</p></section>
        <section><h2>5. Evidence can be a safe reference</h2><p>When appropriate, record a sanitized private reference such as “internal ticket,” “manager feedback,” “course project,” “research supervisor feedback,” or “project dashboard” without copying the restricted source material into BragStack. A reference should still avoid confidential identifiers if you are not allowed to retain them.</p></section>
        <section><h2>6. Use truthful abstractions for metrics</h2><p>If exact metrics are sensitive, use an approved range, percentage, relative improvement, approximate scale, or qualitative outcome only when truthful and permitted. Never invent, inflate, round deceptively, or alter a result to avoid a confidentiality restriction.</p></section>
        <section><h2>7. Shared work requires shared credit</h2><p>Do not describe a team, class, lab, open-source, volunteer, or workplace result as solely yours when other people materially contributed. Distinguish the overall result from your personal contribution and preserve shared credit where it belongs.</p></section>
        <section><h2>8. Third-party personal information</h2><p>Do not upload unnecessary personal information about coworkers, managers, customers, students, educators, recommenders, clients, or other people. If a feature requires limited third-party information, such as an Impact Receipt verification request, provide only what the feature needs and only when you have a reasonable, lawful basis to do so.</p></section>
        <section><h2>9. Education and application material</h2><p>Application prompts, recommendation letters, admissions-review material, scholarship review material, proprietary school content, and student records may be subject to privacy, copyright, academic-integrity, or contractual restrictions. Do not upload or reuse restricted material unless you have permission.</p><p>BragStack's application tools are intended to organize real accomplishments and story candidates. They do not authorize plagiarism, impersonation, fabrication, or violation of an institution's rules concerning AI assistance or outside help.</p></section>
        <section><h2>10. Keep confidential proof private</h2><p>Do not make an accomplishment, Impact Receipt, application artifact, resume item, or Proof Profile content public unless you are permitted to disclose every detail it contains. Assume anything public can be copied, indexed, screenshotted, quoted, or reshared by someone else.</p></section>
        <section><h2>11. Generated outputs inherit source sensitivity</h2><p>A resume bullet, review packet, interview story, application shortlist, essay idea, public profile, or other generated output can still reveal confidential information if the underlying evidence contains it. Review every output before exporting, publishing, submitting, or sending it to another person.</p></section>
        <section><h2>12. Verification is not a legal certification</h2><p>An Impact Receipt confirmation is a statement from the person who responds to the request. It is not an independent audit, credential verification, employment reference, background check, notarization, legal certification, or BragStack guarantee that every underlying fact is true.</p></section>
        <section><h2>13. When not to store something</h2><p>If an agreement, law, policy, school rule, security requirement, or client instruction says information may not be stored in third-party systems, do not put that information in BragStack. Use a sanitized description that you are allowed to retain, or leave the restricted material out entirely.</p></section>
        <section><h2>14. Current adult-use restriction</h2><p>During the current self-service phase, BragStack is intended for users who are at least 18 years old. Do not create an account for a minor or intentionally submit a minor's personal information through the self-service product until BragStack expressly supports that workflow with the appropriate consent and privacy controls.</p></section>
        <section><h2>15. This guidance is not legal advice</h2><p>BragStack does not review or interpret your NDA, employment agreement, school policy, intellectual-property agreement, confidentiality obligation, or application rule. If you are unsure what is permitted, consult the controlling document, an authorized employer or school contact, an information-security or privacy contact, or qualified legal counsel. Product questions can be sent to <a href="mailto:Tobias.scott@usebragstack.com">Tobias.scott@usebragstack.com</a>.</p></section>
      </article>
      <PublicFooter />
    </main>
  );
}

export default NDAGuidancePage;
