export const PACKET_TYPES = [
  {
    value: "performance-review",
    label: "Performance Review Packet",
    shortLabel: "Review Packet",
    description: "Package accomplishments, results, evidence, and growth for a work review or manager check-in.",
    example: "Use it before an annual review, midyear check-in, or performance conversation.",
  },
  {
    value: "promotion",
    label: "Promotion Packet",
    shortLabel: "Promotion Packet",
    description: "Build a documented case for expanded scope, higher level, or increased responsibility.",
    example: "Use it when asking for a promotion, title change, level increase, or advancement review.",
  },
  {
    value: "interview",
    label: "Interview Packet",
    shortLabel: "Interview Packet",
    description: "Turn selected accomplishments into evidence-backed stories and focused interview prep.",
    example: "Use it before an interview to organize stories, results, proof, and questions to prepare for.",
  },
  {
    value: "certification",
    label: "Certification & Licensure Packet",
    shortLabel: "Certification Packet",
    description: "Organize competencies, credentials, continuing education, experience, and supporting proof.",
    example: "Use it for a license renewal, certification review, competency review, or regulated-career submission.",
  },
  {
    value: "program-application",
    label: "Program Application Packet",
    shortLabel: "Program Application",
    description: "Shape your proof around an academic, training, fellowship, residency, or professional program application.",
    example: "Use it when applying to a college program, bootcamp, fellowship, residency, apprenticeship, or leadership program.",
  },
  {
    value: "scholarship",
    label: "Scholarship & Award Packet",
    shortLabel: "Scholarship Packet",
    description: "Connect accomplishments, impact, service, leadership, and evidence to a scholarship or award application.",
    example: "Use it to prepare scholarship essays, award nominations, grant-style personal statements, or selection interviews.",
  },
  {
    value: "portfolio",
    label: "Portfolio & Project Showcase Packet",
    shortLabel: "Portfolio Packet",
    description: "Present selected projects, outcomes, skills, evidence, and recognition as a polished professional showcase.",
    example: "Use it for a recruiter portfolio, client pitch, creative review, project showcase, or professional website companion.",
  },
  {
    value: "career-transition",
    label: "Career Transition Packet",
    shortLabel: "Career Transition",
    description: "Translate existing accomplishments and skills into a clear story for a new role, industry, or career direction.",
    example: "Use it when changing industries, returning to work, moving from school to work, or repositioning transferable skills.",
  },
];

export const DEFAULT_PACKET_OPTIONS = {
  packetType: "performance-review",
  careerArea: "",
  roleTitle: "",
  organization: "",
  targetRole: "",
  targetLevel: "",
  targetOrganization: "",
  selectedEntryIds: [],
  signatureEntryIds: [],
  includeEvidenceReferences: false,
  credentialName: "",
  issuingBody: "",
  reviewType: "Certification / Licensure Review",
  requirementNotes: "",
  programName: "",
  institutionName: "",
  applicationType: "Program application",
  applicationDeadline: "",
  applicationPrompt: "",
  scholarshipName: "",
  sponsorName: "",
  awardFocus: "",
  scholarshipDeadline: "",
  essayPrompt: "",
  portfolioTitle: "",
  portfolioAudience: "",
  portfolioFocus: "",
  projectNotes: "",
  targetIndustry: "",
  transitionGoal: "",
  transferableSkillsFocus: "",
  transitionNotes: "",
  packetNote: "",
  includeNotes: true,
  theme: "modern-minimal",
  brandName: "",
  departmentLabel: "",
  reviewerName: "",
  reviewCycleLabel: "",
  confidential: true,
  exportFormat: "pdf",
};

export function getPacketType(value) {
  return PACKET_TYPES.find((item) => item.value === value) || PACKET_TYPES[0];
}
