export const SEO_LANDING_CONTENT = {
  "/how-it-works": {
    eyebrow: "How BragStack works",
    title: "Capture your work once. Turn it into career proof again and again.",
    description: "BragStack helps you capture accomplishments while they are fresh, connect evidence and skills, create Impact Receipts, and reuse that proof for resumes, reviews, interviews, promotions, and career growth.",
    icon: "receipt",
    points: [
      "Capture the win, your contribution, and the result",
      "Connect evidence, skills, metrics, and shared credit",
      "Reuse documented proof when career opportunities arrive",
    ],
    summaryTitle: "One evidence loop instead of rebuilding your story every time.",
    summaryDescription: "Capture → Prove → Package → Share → Connect. Your private evidence stays connected while you choose what to reuse or publish.",
  },
  "/pricing": {
    eyebrow: "BragStack pricing",
    title: "Start building career proof for free.",
    description: "BragStack has a free tier for building the habit. Upgrade to Pro when you need unlimited proof, advanced career analytics, performance review and promotion builders, exports, integrations, and advanced public profiles.",
    icon: "target",
    points: [
      "Free — $0 with 5 proof entries and 1 Impact Receipt",
      "Pro — $9/month with unlimited proof and advanced career tools",
      "Team and Enterprise options are planned and are not generally available yet",
    ],
    summaryTitle: "Start free. Upgrade when the extra career tools are useful.",
    summaryDescription: "Paid subscriptions renew monthly until canceled when disclosed at checkout. Review the billing terms before purchasing.",
    primaryAction: { label: "Start free", href: "/register" },
  },
  "/resume-accomplishments": {
    eyebrow: "Resume accomplishments",
    title: "Turn real work accomplishments into stronger resume bullets.",
    description: "BragStack helps you capture the situation, action, measurable result, skills, and evidence behind your work so your resume is built from documented accomplishments instead of memory.",
    icon: "file",
    points: [
      "Capture measurable outcomes while they are fresh",
      "Reuse evidence-backed accomplishments across job applications",
      "Keep resume material grounded in work you actually performed",
    ],
  },
  "/career-portfolio": {
    eyebrow: "Career portfolio",
    title: "Build a professional portfolio from evidence, not generic claims.",
    description: "Create a private career proof library and selectively publish accomplishments and Impact Receipts as a professional portfolio for hiring managers, recruiters, clients, and collaborators.",
    icon: "briefcase",
    points: ["Private by default", "Choose exactly what becomes public", "Connect accomplishments to evidence, skills, and measurable impact"],
  },
  "/performance-reviews": {
    eyebrow: "Performance reviews",
    title: "Prepare performance reviews from a year of captured proof.",
    description: "Track wins continuously and organize documented impact into review-ready material instead of rebuilding months of work at the last minute.",
    icon: "trend",
    points: ["Document scope, ownership, impact, and growth", "Capture evidence throughout the review cycle", "Generate review material from recorded accomplishments"],
  },
  "/promotion-packet": {
    eyebrow: "Promotions",
    title: "Make your promotion case with documented impact.",
    description: "Organize evidence around increased scope, leadership, execution, measurable outcomes, and growth so promotion conversations are supported by a clear record of work.",
    icon: "target",
    points: ["Show progression in scope and responsibility", "Highlight measurable business or technical impact", "Package evidence into a promotion-ready narrative"],
  },
  "/interview-preparation": {
    eyebrow: "Interview preparation",
    title: "Prepare interview stories from accomplishments you already documented.",
    description: "Keep real situations, actions, results, metrics, and skills available for behavioral and technical interviews instead of trying to remember your best examples under pressure.",
    icon: "search",
    points: ["Build STAR-style stories from real work", "Find examples by skill, project, or impact", "Use evidence-backed stories for job interviews"],
  },
  "/impact-receipts": {
    eyebrow: "Impact Receipts",
    title: "Create receipts for the work that moved something forward.",
    description: "Impact Receipts structure an accomplishment around your contribution, result, evidence, skills, shared credit, and visibility so important work becomes reusable career proof.",
    icon: "receipt",
    points: ["Attach evidence references", "Record measurable outcomes and shared credit", "Keep receipts private or intentionally publish them"],
    summaryTitle: "The core BragStack proof object.",
    summaryDescription: "A receipt keeps the claim and the support behind it connected so you can reuse the same proof without inventing a new story later.",
  },
  "/career-analytics": {
    eyebrow: "Career analytics",
    title: "See the patterns across your accomplishments and skills.",
    description: "BragStack turns captured proof into a clearer view of recurring skills, categories of impact, evidence coverage, ownership patterns, and career activity over time.",
    icon: "trend",
    points: ["Track recurring skills", "See where your strongest evidence exists", "Identify career signals across your documented work"],
    summaryTitle: "Patterns from your own evidence — not an employee score.",
    summaryDescription: "Career Analytics summarizes the records you captured. It does not predict promotion, hiring, compensation, or employment outcomes.",
  },
  "/public-proof-profiles": {
    eyebrow: "Proof Profiles",
    title: "Share selected career proof without exposing your entire work history.",
    description: "Create a public professional proof profile from only the accomplishments and Impact Receipts you intentionally choose to share with recruiters, hiring managers, clients, or your network.",
    icon: "user",
    points: ["Private account by default", "Granular public visibility", "A shareable proof layer for resumes and portfolios"],
    summaryTitle: "A professional proof page you control.",
    summaryDescription: "Your private workspace does not automatically become public. Publish only the profile details and evidence you intentionally choose.",
  },
  "/professional-packets": {
    eyebrow: "Professional Packets",
    title: "Turn one evidence library into the packet your next career moment needs.",
    description: "Professional Packets help you select and organize documented accomplishments for reviews, promotions, resumes, interviews, and other professional conversations without reconstructing your work history from memory.",
    icon: "file",
    points: [
      "Reuse selected accomplishments instead of copying your entire history",
      "Keep the contribution, result, skills, and evidence connected",
      "Review and edit every packet before sharing or exporting it",
    ],
    summaryTitle: "Different career moment. Same underlying proof.",
    summaryDescription: "Packets reorganize the evidence you choose; they do not create achievements, metrics, credentials, or outcomes you did not record.",
  },
  "/open-to-talk": {
    eyebrow: "Open to Talk",
    title: "Let selected professional proof start a conversation — on your terms.",
    description: "Open to Talk is an opt-in connection path for people who want to discuss proof you intentionally shared. It is designed around user-controlled contact or booking links rather than exposing your private calendar or private workspace.",
    icon: "user",
    points: [
      "Opt in instead of being discoverable by default",
      "Share a contact or booking path you control",
      "Keep private evidence and private calendar details out of the public profile",
    ],
    summaryTitle: "Connection without turning BragStack into a social feed.",
    summaryDescription: "You decide whether to enable a conversation path and what public proof a visitor can see before reaching out.",
  },
  "/freelancers": {
    eyebrow: "BragStack for freelancers",
    title: "Keep a reusable record of the value you delivered across client work.",
    description: "Capture project outcomes, responsibilities, measurable results, approved evidence references, and reusable case-study material across engagements while respecting client confidentiality and contract terms.",
    icon: "briefcase",
    points: [
      "Turn completed projects into reusable evidence",
      "Keep client-safe outcomes and approved proof connected",
      "Prepare stronger case studies, proposals, profiles, and client updates",
    ],
    summaryTitle: "Client work moves fast. Your proof should not disappear with the project.",
    summaryDescription: "Only store or share information you are permitted to retain. BragStack does not override NDAs, client contracts, or confidentiality obligations.",
    secondaryAction: { label: "Confidential work guidance", href: "/nda-safety" },
  },
  "/teams": {
    eyebrow: "Teams · Coming soon",
    title: "Team features are being designed around employee-owned proof.",
    description: "BragStack Teams is planned for organizations that want structured review and recognition workflows without turning individual career evidence into a surveillance stream. Team accounts are not generally available yet.",
    icon: "briefcase",
    points: [
      "Planned shared review templates and centralized billing",
      "Optional confirmation workflows instead of silent monitoring",
      "Bounded organization analytics separated from individual evidence ownership",
    ],
    status: "COMING SOON",
    summaryTitle: "Support growth without owning an employee's career history.",
    summaryDescription: "The team roadmap is intentionally conservative. Availability, features, controls, and pricing may change before launch.",
    primaryAction: { label: "Join the Team waitlist", href: "/team-waitlist" },
    secondaryAction: { label: "See the individual product", href: "/how-it-works" },
  },
  "/use-cases": {
    eyebrow: "BragStack use cases",
    title: "Useful whenever your progress needs to be explained clearly.",
    description: "Use the same evidence record for performance reviews, promotions, resumes, interviews, freelance work, career changes, professional portfolios, and other moments where remembering the details matters.",
    icon: "target",
    points: [
      "Performance reviews and promotion conversations",
      "Resumes, interviews, portfolios, and job searches",
      "Freelance projects, professional development, and career transitions",
    ],
    summaryTitle: "One record, many professional moments.",
    summaryDescription: "BragStack helps organize your own evidence. It does not guarantee hiring, promotion, admission, compensation, or selection outcomes.",
  },
  "/contact": {
    eyebrow: "Contact BragStack",
    title: "Need help, have a question, or want to talk about BragStack?",
    description: "Use the right BragStack address so your message reaches the right queue. Do not email passwords, payment-card numbers, API keys, confidential employer evidence, or other secrets.",
    icon: "user",
    points: [
      "General and business questions — contact@usebragstack.com",
      "Product support — support@usebragstack.com",
      "Privacy — privacy@usebragstack.com · Security — security@usebragstack.com · Billing — billing@usebragstack.com",
    ],
    summaryTitle: "A real contact path, not a dead footer link.",
    summaryDescription: "For account-specific support, include the email on the account and a description of the issue, but never send your password or sensitive proof content by email.",
    primaryAction: { label: "Email BragStack", href: "mailto:contact@usebragstack.com?subject=BragStack%20question" },
    secondaryAction: { label: "Open Docs", href: "/docs" },
  },
  "/team-waitlist": {
    eyebrow: "BragStack Teams · Waitlist",
    title: "Interested in BragStack for a team? Tell us what you actually need.",
    description: "Team functionality is still in development. Joining the waitlist expresses interest; it does not create a paid subscription, reserve a launch date, or guarantee any specific feature.",
    icon: "user",
    points: [
      "Tell us your team size and review workflow",
      "Share which confirmation, reporting, or governance controls matter most",
      "No payment is required to express interest",
    ],
    status: "COMING SOON",
    summaryTitle: "Help shape the team product before it launches.",
    summaryDescription: "We are prioritizing employee ownership, selective confirmation, privacy, and bounded analytics rather than workplace surveillance.",
    primaryAction: { label: "Join by email", href: "mailto:contact@usebragstack.com?subject=BragStack%20Team%20waitlist" },
    secondaryAction: { label: "Read about Teams", href: "/teams" },
  },
  "/enterprise": {
    eyebrow: "BragStack Enterprise · Early conversations",
    title: "Planning a larger rollout? Start with requirements, not promises.",
    description: "Enterprise capabilities are not generally available yet. BragStack is open to early conversations about identity, governance, retention, audit, integrations, support, and organization controls while preserving the individual evidence-ownership model.",
    icon: "briefcase",
    points: [
      "Discuss identity, governance, retention, and audit requirements",
      "Define privacy boundaries between individual proof and organization reporting",
      "Evaluate integration and support needs before any commitment",
    ],
    status: "EARLY ACCESS DISCUSSIONS",
    summaryTitle: "Enterprise is a roadmap conversation today.",
    summaryDescription: "Features, pricing, availability, implementation timelines, and contractual terms are subject to future agreement and may change.",
    primaryAction: { label: "Contact BragStack", href: "mailto:contact@usebragstack.com?subject=BragStack%20Enterprise" },
    secondaryAction: { label: "Trust & privacy", href: "/security" },
  },
};

export function getSeoLandingPage(path) {
  return SEO_LANDING_CONTENT[path] || null;
}
