export const SEO_LANDING_CONTENT = {
  "/how-it-works": { eyebrow: "How BragStack works", title: "Capture your work once. Turn it into career proof again and again.", description: "BragStack helps you capture accomplishments while they are fresh, connect evidence and skills, create Impact Receipts, and reuse that proof for resumes, reviews, interviews, promotions, and career growth.", icon: "receipt", points: ["Capture the win, your contribution, and the result", "Connect evidence, skills, metrics, and shared credit", "Reuse documented proof when career opportunities arrive"] },
  "/pricing": { eyebrow: "BragStack pricing", title: "Start building career proof for free.", description: "BragStack has a free tier for building the habit. Upgrade to Pro when you need unlimited proof, advanced career analytics, performance review and promotion builders, exports, integrations, and advanced public profiles.", icon: "target", points: ["Free — $0 with 5 proof entries and 1 Impact Receipt", "Pro — $9/month with unlimited proof and advanced career tools", "Team and Enterprise options for organizations are planned"] },
  "/resume-accomplishments": { eyebrow: "Resume accomplishments", title: "Turn real work accomplishments into stronger resume bullets.", description: "BragStack helps you capture the situation, action, measurable result, skills, and evidence behind your work so your resume is built from documented accomplishments instead of memory.", icon: "file", points: ["Capture measurable outcomes while they are fresh", "Reuse evidence-backed accomplishments across job applications", "Keep resume material grounded in work you actually performed"] },
  "/career-portfolio": { eyebrow: "Career portfolio", title: "Build a professional portfolio from evidence, not generic claims.", description: "Create a private career proof library and selectively publish accomplishments and Impact Receipts as a professional portfolio for hiring managers, recruiters, clients, and collaborators.", icon: "briefcase", points: ["Private by default", "Choose exactly what becomes public", "Connect accomplishments to evidence, skills, and measurable impact"] },
  "/performance-reviews": { eyebrow: "Performance reviews", title: "Prepare performance reviews from a year of captured proof.", description: "Track wins continuously and organize documented impact into review-ready material instead of rebuilding months of work at the last minute.", icon: "trend", points: ["Document scope, ownership, impact, and growth", "Capture evidence throughout the review cycle", "Generate review material from recorded accomplishments"] },
  "/promotion-packet": { eyebrow: "Promotion packet", title: "Make your promotion case with documented impact.", description: "Organize evidence around increased scope, leadership, execution, measurable outcomes, and growth so promotion conversations are supported by a clear record of work.", icon: "target", points: ["Show progression in scope and responsibility", "Highlight measurable business or technical impact", "Package evidence into a promotion-ready narrative"] },
  "/interview-preparation": { eyebrow: "Interview preparation", title: "Prepare interview stories from accomplishments you already documented.", description: "Keep real situations, actions, results, metrics, and skills available for behavioral and technical interviews instead of trying to remember your best examples under pressure.", icon: "search", points: ["Build STAR-style stories from real work", "Find examples by skill, project, or impact", "Use evidence-backed stories for job interviews"] },
  "/impact-receipts": { eyebrow: "Impact Receipts", title: "Create receipts for the work that moved something forward.", description: "Impact Receipts structure an accomplishment around your contribution, result, evidence, skills, shared credit, and visibility so important work becomes reusable career proof.", icon: "receipt", points: ["Attach evidence references", "Record measurable outcomes and shared credit", "Keep receipts private or intentionally publish them"] },
  "/career-analytics": { eyebrow: "Career analytics", title: "See the patterns across your accomplishments and skills.", description: "BragStack turns captured proof into a clearer view of recurring skills, categories of impact, evidence coverage, ownership patterns, and career activity over time.", icon: "trend", points: ["Track recurring skills", "See where your strongest evidence exists", "Identify career signals across your documented work"] },
  "/public-proof-profiles": { eyebrow: "Public proof profiles", title: "Share selected career proof without exposing your entire work history.", description: "Create a public professional proof profile from only the accomplishments and Impact Receipts you intentionally choose to share with recruiters, hiring managers, clients, or your network.", icon: "user", points: ["Private account by default", "Granular public visibility", "A shareable proof layer for resumes and portfolios"] }
};
export function getSeoLandingPage(path){return SEO_LANDING_CONTENT[path]||null;}
